DROP TABLE IF EXISTS HISTORICO_SINCRONIZACAO_ONBOARDING;
DROP TABLE IF EXISTS NOTIFICACAO_ONBOARDING;

DROP TABLE IF EXISTS VALIDACAO_PRECADASTRO;
DROP TABLE IF EXISTS PRECADASTRO;


CREATE TABLE NOTIFICACAO_ONBOARDING (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hash VARCHAR(64) UNIQUE NOT NULL,
    tim_notificacao TIMESTAMP NOT NULL,    
    tim_sincronizacao TIMESTAMP ,
    situacao_atual VARCHAR(60) NOT NULL
);
-- Add indexes
CREATE INDEX idx_NOTIFICACAO_hash ON NOTIFICACAO_ONBOARDING(hash);

-- Create HISTORICO_SINCRONIZACAO_ONBOARDING table
CREATE TABLE HISTORICO_SINCRONIZACAO_ONBOARDING (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hash VARCHAR(64) NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    situacao VARCHAR(60) NOT NULL,
    mensagem_erro VARCHAR(5000)

);
CREATE INDEX idx_HISTORICO_SINCRONIZACAO_ONBOARDING_hash ON HISTORICO_SINCRONIZACAO_ONBOARDING(hash);


-- Create PRECADASTRO table
CREATE TABLE PRECADASTRO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hash VARCHAR(64) UNIQUE NOT NULL,
    jso_dados_originais JSON NOT NULL,
    num_cpf VARCHAR(14),
    nome VARCHAR(200),
    nome_social VARCHAR(200),
    data_nascimento DATE,
    nome_mae VARCHAR(200),
    numero_documento VARCHAR(30),
    pais_origem VARCHAR(100),
    orgao_emissor VARCHAR(10),
    uf VARCHAR(2),
    data_expedicao DATE,
    data_vencimento DATE,
    situacao VARCHAR(60) NOT NULL,
    data_cadastro TIMESTAMP ,
    data_validacao TIMESTAMP 

);
-- Add indexes
CREATE INDEX idx_PRECADASTRO_hash ON PRECADASTRO(hash);

-- Create VALIDACAO_PRECADASTRO table
CREATE TABLE VALIDACAO_PRECADASTRO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_pre_cadastro BIGINT NOT NULL,
    tim_validacao TIMESTAMP NOT NULL,    
    campo VARCHAR(100) NOT NULL,
    mensagem VARCHAR(500) NOT NULL,


    FOREIGN KEY (id_pre_cadastro) REFERENCES PRECADASTRO(id)
);
CREATE INDEX idx_VALIDACAO_PRECADASTRO_id_pre_cadastro ON VALIDACAO_PRECADASTRO(id_pre_cadastro);

